server:
  port: 8081

spring:
  application.name: customerservice
  main:
    allow-bean-definition-overriding: true
  flyway:
    locations: classpath:db/migration
    default-schema: customer
    enabled: true
  datasource:
    driver-class-name: 'org.postgresql.Driver'
    url: jdbc:postgresql://localhost:5432/customer
    username: postgres
    password: iamroot
  jpa:
    show-sql: true
    properties:
      hibernate:
        show_sql: false
        ddl-auto: validate
        default_schema: customer
        format_sql: true
    generate-ddl: true
#  mvc:
#    hiddenmethod:
#      filter:
#        enabled: true
#    throw-exception-if-no-handler-found: true
#    static-path-pattern: /static

logging:
  level:
    root: info