server:
  port: 8082

spring:
  application.name: deposit
  main:
    allow-bean-definition-overriding: true
  flyway:
    locations: classpath:db/migration
    default-schema: deposit
    enabled: true
  datasource:
    driver-class-name: 'org.postgresql.Driver'
    url: jdbc:postgresql://localhost:5432/deposit
    username: postgres
    password: iamroot
  jpa:
    show-sql: true
    properties:
      hibernate:
        show_sql: true
        ddl-auto: validate
        default_schema: deposit
        format_sql: true
    generate-ddl: true
  mvc:
    hiddenmethod:
      filter:
        enabled: true

logging:
  level:
    root: info